package proj.ctworld.core.orm;
// Generated by Hibernate Tools 4.3.5.Final

import java.util.*;
import javax.persistence.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemMessage generated by hbm2java
 */
@Entity
@Table(name = "system_message")
public class SystemMessage implements java.io.Serializable {

	private Long smId;
	private int smCode;
	private String smMessage;

	public SystemMessage() {
	}

	public SystemMessage(int smCode, String smMessage) {
		this.smCode = smCode;
		this.smMessage = smMessage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sm_id", unique = true, nullable = false)
	public Long getSmId() {
		return this.smId;
	}

	public void setSmId(Long smId) {
		this.smId = smId;
	}

	@Column(name = "sm_code", nullable = false)
	public int getSmCode() {
		return this.smCode;
	}

	public void setSmCode(int smCode) {
		this.smCode = smCode;
	}

	@Column(name = "sm_message", nullable = false, length = 45)
	public String getSmMessage() {
		return this.smMessage;
	}

	public void setSmMessage(String smMessage) {
		this.smMessage = smMessage;
	}

}
